# Métriques StatsD d'Airflow -> Prometheus, avec dag_id / task_id / état en labels.
mappings:
  - match: "airflow.dagrun.duration.*.*"
    name: airflow_dagrun_duration
    labels: {status: "$1", dag_id: "$2"}
  - match: "airflow.ti.finish.*.*.*"
    name: airflow_ti_finish
    labels: {dag_id: "$1", task_id: "$2", state: "$3"}
  - match: "airflow.dag.*.*.duration"
    name: airflow_task_duration
    labels: {dag_id: "$1", task_id: "$2"}
  - match: "airflow.dag_processing.last_duration.*"
    name: airflow_dag_processing_last_duration
    labels: {dag_file: "$1"}
