apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: processing
labels:
  - pairs: {app.kubernetes.io/part-of: waba, waba/domain: processing}
    includeSelectors: false
resources:
  - spark-operator
  - iceberg-rest.yaml
  - airflow.yaml
  - streaming.yaml
  - ingress.yaml
